name: Tag Release

on:
  pull_request:
    types: [closed]
    
# ðŸ‘‡ The caller must grant write perms to push tags
permissions:
  contents: write        # allows creating/pushing tags
  pull-requests: read

jobs:
  release:
    uses: clouddrove/github-shared-workflows/.github/workflows/tag-release.yml@master
    with:
      target_branch: master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}